apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 984821113546.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 984821113546.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: e09b46ed
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
